// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebhukzjhtfbcmtqzsowb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViaHVrempodGZiY210cXpzb3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTEzNjMsImV4cCI6MjA2NTM2NzM2M30.ArFqK7a9t3ad-O882daNFtxPd4eHH7tZS37YVapycww";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);